CREATE TABLE USERS(
    USERID VARCHAR(10) NOT NULL,
    FIRST_NAME TEXT NOT NULL,
    LAST_NAME TEXT NOT NULL,
    DATE_REGISTERED DATETIME NOT NULL,
    PRIMARY KEY(USERID)
)

CREATE TABLE POST (
    POSTID VARCHAR(10) NOT NULL,
    TITLE TEXT NOT NULL,
    CONTENT TEXT NOT NULL,
    DATE_CREATED DATETIME NOT NULL, 
    AUTHORID INTEGER AUTOINCREMENT NOT NULL,
    PRIMARY KEY(POSTID),
    FOREIGN KEY (AUTHORID) REFERENCES USERS(USERID)
)

CREATE TABLE REGISTRATION (
    REGID VARCHAR NOT NULL,
    PLAYER_NAME TEXT NOT NULL,
    FAVOURITE_SPORT TEXT NOT NULL,
    TEAM_NAME TEXT NOT NULL,
    PLAYERID INTEGER AUTOINCREMENT NOT NULL,
    PRIMARY KEY(REGID),
    FOREIGN KEY (PLAYERID) REFERENCES USERS(USERID)
)

