CREATE TABLE USER(
    USERID TEXT NOT NULL,
    FIRST_NAME TEXT NOT NULL,
    LAST_NAME TEXT NOT NULL,
    USERNAME TEXT NOT NULL,
    PASS_WORD PASSWORD NOT NULL
    DATE_OF_BIRTH DATETIME NOT NULL,
    DATE_REGISTERED DATETIME NOT NULL,
    PRIMARY KEY(USERID)
)

CREATE TABLE POST (
    POSTID TEXT NOT NULL,
    POST_TITLE TEXT NOT NULL,
    POST_DESCRIPTION TEXT NOT NULL,
    DATE_CREATED DATETIME NOT NULL, 
    AUTHORID TEXT NOT NULL,
    PRIMARY KEY(POSTID),
    FOREIGN KEY (AUTHORID) REFERENCES USER(USERID)
)

CREATE TABLE SPORT_REGISTRATION (
    REGID TEXT NOT NULL,
    PLAYER_NAME TEXT NOT NULL,
    FAVOURITE_SPORT TEXT NOT NULL,
    TEAM_NAME TEXT NOT NULL,
    PLAYERID TEXT NOT NULL,
    PRIMARY KEY(REGID),
    FOREIGN KEY (PLAYERID) REFERENCES USERS(USERID)
)

CREATE TABLE SCHEDULE (
    SCHEDULEID
    GAME_DATE
    TEAMS_PLAYING
    VENUE
    
)
